/*******************************************
 *
 * Author: HzChen - hzchen_cs@gwmail.gwu.edu
 *
 *
 * Last modified:	03-25-2014 22:25
 *
 * Filename:		test.c
 *
 * Description: 
 *
 *
 *
 * Consider all integer combinations of ab for 2 ≤ a ≤ 5 and 2 ≤ b ≤ 5:
 *
 *     22=4, 23=8, 24=16, 25=32
 *     32=9, 33=27, 34=81, 35=243
 *     42=16, 43=64, 44=256, 45=1024
 *     52=25, 53=125, 54=625, 55=3125
 *
 * If they are then placed in numerical order, with any repeats removed, 
 * we get the following sequence of 15 distinct terms:
 *
 * 4, 8, 9, 16, 25, 27, 32, 64, 81, 125, 243, 256, 625, 1024, 3125
 *
 * How many distinct terms are in the sequence generated by ab for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
 *
 *
 *
******************************************/
#include <stdlib.h>
#include <stdio.h>
#include <math.h>

#define unlikely(x)     __builtin_expect(!!(x), 0)
#define likely(x)     	__builtin_expect(!!(x), 1)

#define SZ	100
#define TOTAL	((SZ-1) * (SZ-1))


int main(int argc, char** argv)
{

	int n, e1, e2, dup=0, b2, i, j;

	int (*arr)[SZ+1][SZ+1] = (int (*)[SZ+1][SZ+1])malloc(sizeof(int) * (SZ+1) * (SZ+1));

	for(i=0; i <= SZ; i++)
		for( j = 0; j <= SZ; j++)
			(*arr)[i][j] = 0;
	/*
	 *	1:	b/c			a1 ^ b1	= a2 ^ b2, 
	 *		==>	  n ^ (e1 * b1)	= n ^ (e2 * b2), assume e1 < e2
	 *
	 *	2:	b/c			2 <=	a1 	<= 100
	 *		==>			2 <=  n ^ e <= 100
	 *		==>			1 <= 	e	<= lg(100)/lg(n)				
	 *
	 *	3:	b/c			2 <=  e * b	<= 100
	 *		==>			2 <=	b	<= 100/e
	 */
	for( n = 2; n <= SZ; n++)
	{
		int upper = (int)(log(SZ) / log(n));
		for( e1 = 1; e1 <= upper-1; e1++)
			for( e2 = e1+1; e2 <= upper; e2++)
			{
				int range_b = (int)(SZ/e2);
				for(b2 = 2; b2 <= range_b; b2++)
				{
					int b1 = e2 * b2 / e1;
					if(!(*arr)[(int)(pow(n, e1))][b1])
					{
						printf("%d^%d = %d^%d\n", (int)pow(n, e1), (int)b1, (int)pow(n, e2), b2);
						(*arr)[(int)(pow(n, e1))][b1] = 1;
					}
				}
			}
	}

	for(i=0; i <= SZ; i++)
		for( j = 0; j <= SZ; j++)
			dup += (*arr)[i][j];


	printf("num of duplication: %d\n", dup);
	printf("num of total: %d\n", TOTAL);
	printf("num of distinct result: %d\n", TOTAL - dup);

	free(arr);

	return EXIT_SUCCESS;
}

